#include "dc/export/AllExport.hh"
#include "dc/export/ccafeopq_events.hh"
#include "dc/services/ContextEventManager/eventCons.hh"


ccafeopq::event::ComponentFactoryEventImplementation	test_ccafeopq_ComponentFactoryEventImplementation;
ccafeopq::event::ComponentFactoryEventProcessor	test_ccafeopq_ComponentFactoryEventProcessor;
ccafeopq::event::ComponentInstanceAddedEventImplementation	test_ccafeopq_ComponentInstanceAddedEventImplementation;
ccafeopq::event::ComponentInstanceAddedEventProcessor	test_ccafeopq_ComponentInstanceAddedEventProcessor;
ccafeopq::event::ComponentInstanceAddRequestEventImplementation	test_ccafeopq_ComponentInstanceAddRequestEventImplementation;
ccafeopq::event::ComponentInstanceAddRequestEventProcessor	test_ccafeopq_ComponentInstanceAddRequestEventProcessor;
ccafeopq::event::ComponentInstanceDeletedEventImplementation	test_ccafeopq_ComponentInstanceDeletedEventImplementation;
ccafeopq::event::ComponentInstanceDeletedEventProcessor	test_ccafeopq_ComponentInstanceDeletedEventProcessor;
ccafeopq::event::ComponentInstanceDeleteRequestEventImplementation	test_ccafeopq_ComponentInstanceDeleteRequestEventImplementation;
ccafeopq::event::ComponentInstanceDeleteRequestEventProcessor	test_ccafeopq_ComponentInstanceDeleteRequestEventProcessor;
ccafeopq::event::ContextConnectionEventImplementation	test_ccafeopq_ContextConnectionEventImplementation;
ccafeopq::event::ContextConnectionEventProcessor	test_ccafeopq_ContextConnectionEventProcessor;
ccafeopq::event::ContextEventImplementation	test_ccafeopq_ContextEventImplementation;
ccafeopq::event::ContextEventListenerWrap	test_ccafeopq_ContextEventListenerWrap;
ccafeopq::event::PortActivityEventImplementation	test_ccafeopq_PortActivityEventImplementation;
ccafeopq::event::PortActivityEventProcessor	test_ccafeopq_PortActivityEventProcessor;
ccafeopq::event::PortDefinitionEventImplementation	test_ccafeopq_PortDefinitionEventImplementation;
ccafeopq::event::PortDefinitionEventProcessor	test_ccafeopq_PortDefinitionEventProcessor;
int main () { return 0 ; }
